namespace VRage.Game
{
	public enum MyCubeTopology
	{
		Box,
		Slope,
		Corner,
		InvCorner,
		StandaloneBox,
		RoundedSlope,
		RoundSlope,
		RoundCorner,
		RoundInvCorner,
		RotatedSlope,
		RotatedCorner,
		Slope2Base,
		Slope2Tip,
		Corner2Base,
		Corner2Tip,
		InvCorner2Base,
		InvCorner2Tip,
		HalfBox,
		HalfSlopeBox,
		HalfSlopeInverted,
		HalfSlopeCorner,
		HalfSlopeCornerInverted,
		SlopedCornerTip,
		SlopedCornerBase,
		SlopedCorner,
		HalfSlopedCornerBase,
		HalfCorner,
		CornerSquare,
		CornerSquareInverted,
		HalfSlopedCorner
	}
}
