namespace Sandbox.Engine.Multiplayer
{
	public enum MyMessageId : byte
	{
		FLUSH = 2,
		RPC = 3,
		REPLICATION_CREATE = 4,
		REPLICATION_DESTROY = 5,
		SERVER_DATA = 6,
		SERVER_STATE_SYNC = 7,
		CLIENT_READY = 8,
		CLIENT_ACKS = 17,
		CLIENT_UPDATE = 9,
		REPLICATION_READY = 10,
		REPLICATION_STREAM_BEGIN = 11,
		REPLICATION_ISLAND_DONE = 18,
		REPLICATION_REQUEST = 19,
		JOIN_RESULT = 12,
		WORLD_DATA = 13,
		CLIENT_CONNECTED = 14,
		WORLD = 20,
		PLAYER_DATA = 21
	}
}
